---
name: Module Three Task Three
on:
   push:
      branches:
      - master
      tags:
        - "*.*.*"*
   schedule:
      - cron: '0 0 * * *'
jobs:
   Explore-GitHub-Actions:
      runs-on: ubuntu-latest
      steps:
         - run: |
              git clone https://github.com/mittsahl/validation
         - run: |
              brew install hugo         
         - run: |
              cd validation/module3_task3
              make build
              make package
         - name: Archive artifacts
           uses: actions/upload-artifact@v2
           with:
             path: |
               validation/module3_task3/awesome-website.zip 
         - name: Release
           uses: softprops/action-gh-release@v1
           if: startsWith(github.ref, 'refs/tags/')
           with:
            files:
              validation/module3_task3/awesome-website.zip
              validation/module3_task3/DEPLOY.md         
