---
name: Module Three Task Two
on:
   push:
      branches:
      - master
   schedule:
      - cron: '0 0 * * *'
jobs:
   Explore-GitHub-Actions:
      runs-on: ubuntu-latest
      steps:
         - run: |
              git clone https://github.com/mittsahl/validation
         - run: |
              brew install hugo         
         - run: |
              cd validation/module3_task2
              make build
              make package
         - name: Archive artifacts
           uses: actions/upload-artifact@v2
           with:
             path: |
               validation/module3_task2/awesome-website           
