name: Module3_Task0
on: [push]
    schedule:
      - cron: "0 0 * * *"
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:   
      - run: |
          cd module3_task0
          make help
