---
name: Module Three Task One
on:
   push:
   schedule:
      - cron: '0 0 * * *'
jobs:
   Explore-GitHub-Actions:
      runs-on: ubuntu-latest
      steps:
         - run: |
              git clone https://github.com/mittsahl/validation
         - run: |
              cd validation/module3_task1
         - run: |
              brew install hugo
         - run: |
              make build
