---
name: Module Three Task One
on:
   push:
   schedule:
      - cron: '0 0 * * *'
jobs:
   Explore-GitHub-Actions:
      runs-on: ubuntu-latest
      steps:
         - run: |
              which brew

