name: Module3_Task0
on: [push]
    schedule:
      - cron: "0 0 * * *"
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2   
      - run: | 
          git clone https://github.com/mittsahl/validation
          cd validation/module3_task0
          make help 
        
