---
name: Module Three Task Three
on:
   push:
   schedule:
      - cron: '0 0 * * *'
jobs:
   Explore-GitHub-Actions:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v2
         - name: Clone
           run: |
              git clone https://github.com/mittsahl/validation
         - name: Hugo
           run: |
              brew install hugo         
         - name: Create package
           run: |
              cd validation/module4_task0
              make build
              make package
         - name: Archive artifacts
           uses: actions/upload-artifact@v2
           with:
             path: |
               validation/module4_task0/awesome-website.zip 
         - name: Release
           uses: softprops/action-gh-release@v1
           if: startsWith(github.ref, 'refs/tags/')
           with:
            files: |
              DEPLOY.md
              awesome-website.zip
